# pandas Code Examples

Use this notebook with slide 8 of the Real World Data Wrangling session. By the end, learners can load a CSV, pull one column as a Series, filter rows, and update values with `.loc`.

## 1. Import pandas

The alias `pd` is the common convention, so most examples in the pandas documentation use it.

In [1]:
# Import the pandas module to our code and reference it as pd
import pandas as pd

## 2. Load `data.csv` into a DataFrame

A DataFrame is pandas' table object. The file is in the same folder as this notebook, so the relative path is just `data.csv`.

In [2]:
# Load a CSV file data.csv into a pandas DataFrame instance called df
df = pd.read_csv('data.csv')
df

    Name  Age      City      status
0  Aisha    8   Jakarta  Unassigned
1   Budi   10   Bandung  Unassigned
2  Carla   11  Surabaya  Unassigned
3   Dewi    7   Jakarta  Unassigned
4  Ethan   16   Chicago  Unassigned
5  Farah   35   Bandung  Unassigned
6   Gita    9  Surabaya  Unassigned
7   Hadi   42   Jakarta  Unassigned

## 3. Select one column as a Series

A Series is pandas' one-column object. The bracket style is the safer habit because it also works for column names with spaces.

In [3]:
# Get a Series from that DataFrame object, which is the entire "Age" column.
ages = df['Age']
ages

0     8
1    10
2    11
3     7
4    16
5    35
6     9
7    42
Name: Age, dtype: int64

In [4]:
# Alternatively, you can also get it with the dot operator.
# It does not work when the column name has spaces, and does not look
# particularly nice when there are capital letters.
ages = df.Age
ages

0     8
1    10
2    11
3     7
4    16
5    35
6     9
7    42
Name: Age, dtype: int64

## 4. Filter rows with a condition

Before running the next cell, predict how many rows have `Age < 11`.

In [5]:
# Select rows where the value of the column "Age" is <11
children_df = df[df['Age'] < 11]
children_df

    Name  Age      City      status
0  Aisha    8   Jakarta  Unassigned
1   Budi   10   Bandung  Unassigned
3   Dewi    7   Jakarta  Unassigned
6   Gita    9  Surabaya  Unassigned

## 5. Update selected rows with `.loc`

Use `.loc[row_condition, column_name]` when you want to update a specific column for the rows that match a condition.

In [6]:
# Update the "status" column of rows where the column "Age" is <11 to "Children".
# Notice the use of .loc.
df.loc[df['Age'] < 11, 'status'] = 'Children'
df

    Name  Age      City      status
0  Aisha    8   Jakarta    Children
1   Budi   10   Bandung    Children
2  Carla   11  Surabaya  Unassigned
3   Dewi    7   Jakarta    Children
4  Ethan   16   Chicago  Unassigned
5  Farah   35   Bandung  Unassigned
6   Gita    9  Surabaya    Children
7   Hadi   42   Jakarta  Unassigned

## Quick check

This final cell counts the status values so learners can confirm exactly which rows changed.

In [7]:
df['status'].value_counts()

status
Children      4
Unassigned    4
Name: count, dtype: int64